version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: echo "Testing"
      - run: yarn test
workflows:
  version: 2
  test_build:
    jobs:
      - build
      - test